Remove latest <release/> if version higher than current.
This fixes this error:

> Error: Appstream: 'E:org.gimp.GIMP.metainfo.xml:releases-not-in-order The releases are not sorted in a latest to oldest version order. This is required as some tools will assume that the latest version is always at the top. Sorting releases also increases overall readability of the metainfo file.'

The problem was that we may add a snapshot <release/> (in the next CLI
command) at the end of the <releases/> listing, but if we already
prepared a release tag for the upcoming version, versions will be
wrongly ordered (because the snapshot will necessarily be before the
upcoming release version).

Note that this specific error would also have been handled by changing
the release date to today in the AppStream metadata, but then this error
will pop out again later.

I am also outputting the full contents of the AppStream metadata in the
end of the commands listing for easier debugging, since we are making
some pretty flimsy search-and-replace commands, we may have more
problems in the future, so it's not a bad idea to be able to check the
contents when unsure.